### PR TITLE
`Key` has been removed from FormattingOptions

### PR DESCRIPTION
**Pull request by tw4452852**
Signed-off-by: Tw <tw19881113@gmail.com>

### CODE REVIEW

**Comment by fhs** [comment]
I'm afraid this breaks compatibility with other LSP servers.

**Comment by tw4452852** [comment]
Hi @fhs ,

I did a test on `gopls` and `rust-analyzer`, they work fine.

**Review by fhs — DISMISSED** [review]
:+1:

**Comment by fhs** [comment]
How come the tests are failing?

**Comment by tw4452852** [comment]
Hi @fhs 

I don't know the other case, `TestFormattingOptions` should work now.

**Review by fhs — APPROVED** [review]

**Pull request merged**
